#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
CYAN="\033[1;36m"
RESET="\033[0m"

echo -e "${CYAN}Добро пожаловать в систему личных сервисов!${RESET}"
echo -e "${PURPLE}Текущее время: $(date '+%Y-%m-%d %H:%M:%S')${RESET}"
echo -e "${BLUE}Версия ядра системы: $(uname -r)${RESET}"
echo -e "${GREEN}Адрес проекта: https://github.com/qljsyph/bash-script версия v1.2.5beta ${RESET}"

check_mihomo_service() {
    echo -e "\n${CYAN}Проверка статуса сервиса '虚空终端' (mihomo):${RESET}"
    if systemctl is-active --quiet mihomo; then
        echo -e "${GREEN}Сервис запущен${RESET}"
    else
        echo -e "${RED}Сервис не запущен${RESET}"
    fi
}

check_system_resources() {
    echo -e "\n${CYAN}Информация о системных ресурсах:${RESET}"
    CPU_INFO=$(top -bn1 | grep "Cpu(s)" | awk '{if (NF >= 8) printf "Использование: %.1f%%, Свободно: %.1f%%", $2, $8}')
    echo -e "${BLUE}Состояние CPU: ${RESET}${CPU_INFO}"
    MEM_INFO=$(free -h | awk '/^Mem/ {printf "%s/%s (%.1f%%)", $3, $2, $3/$2*100}')
    echo -e "${BLUE}Использование памяти: ${RESET}${MEM_INFO}"
    DISK_INFO=$(df -h / 2>/dev/null | awk 'NR==2 {print $5}')
    echo -e "${BLUE}Использование диска: ${RESET}${DISK_INFO}"
}

check_network() {
    echo -e "\n${CYAN}Информация о сети:${RESET}"
    DEFAULT_GATEWAY=$(ip route | awk '/default/ {print $3}')
    GATEWAY_INTERFACE=$(ip route | awk '/default/ {print $5}')
    [[ -n "$DEFAULT_GATEWAY" ]] && echo -e "${BLUE}Шлюз по умолчанию: ${RESET}${DEFAULT_GATEWAY}\n${BLUE}Интерфейс шлюза: ${RESET}${GATEWAY_INTERFACE}" || echo -e "${RED}Информация о шлюзе по умолчанию не найдена!${RESET}"
    if [[ -f /run/systemd/resolve/resolv.conf ]]; then
        DNS_SERVERS=$(grep '^nameserver' /run/systemd/resolve/resolv.conf | awk '{print $2}')
    else
        DNS_SERVERS=$(grep '^nameserver' /etc/resolv.conf | awk '{print $2}')
    fi
    [[ -n "$DNS_SERVERS" ]] && echo -e "${BLUE}DNS серверы: ${RESET}\n$DNS_SERVERS" || echo -e "${RED}Информация о DNS серверах не найдена!${RESET}"
}

check_mihomo_service
check_system_resources
check_network
