#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
CYAN="\033[1;36m"
RESET="\033[0m"

echo -e "${CYAN}Добро пожаловать в систему личных сервисов!${RESET}"
echo -e "${PURPLE}Текущее время: $(date '+%Y-%m-%d %H:%M:%S')${RESET}"
echo -e "${BLUE}Версия ядра системы: $(uname -r)${RESET}"
echo -e "${GREEN}Адрес проекта: https://github.com/qljsyph/bash-script  версия v1.2.5beta${RESET}"

check_singbox() {
if command -v sing-box >/dev/null 2>&1; then
    CURRENT_VERSION=$(sing-box version 2>/dev/null | head -n 1 | cut -d ' ' -f 3 || echo "неизвестная версия")
    CURRENT_VERSION_TYPE=$(echo "$CURRENT_VERSION" | grep -oE '(alpha|beta|rc)' || echo "stable")
    CURRENT_VERSION="${CURRENT_VERSION#v}"

    ALL_VERSIONS=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases | grep -Po '"tag_name": "\K.*?(?=")')

    if [[ "$CURRENT_VERSION_TYPE" == "stable" ]]; then
        LATEST_VERSION=$(echo "$ALL_VERSIONS" | grep -vE '(alpha|beta|rc)' | head -n 1)
    else
        LATEST_VERSION=$(echo "$ALL_VERSIONS" | grep -E "$CURRENT_VERSION_TYPE" | head -n 1)
    fi

    LATEST_VERSION="${LATEST_VERSION#v}"

    echo -e "${YELLOW}Информация о версии Sing-box:${RESET}"
    echo -e "${BLUE}Текущая версия:${RESET} ${CURRENT_VERSION} ${BLUE}Последняя версия:${RESET} ${LATEST_VERSION}"

    if [[ -n "$LATEST_VERSION" ]]; then
        if [[ "$CURRENT_VERSION" == "$LATEST_VERSION" ]]; then
            echo -e "${GREEN}Sing-box уже обновлен до последней версии${RESET}"
        else
            echo -e "${YELLOW}Обнаружена новая версия! Рекомендуется обновить Sing-box${RESET}"
        fi
    else
        echo -e "${RED}Не удалось получить информацию о последней версии Sing-box${RESET}"
    fi
else
    echo -e "${RED}Sing-box не установлен${RESET}"
fi
}

check_services() {
  if systemctl list-units --type=service --all | grep -q "nftables-singbox.service"; then
    if systemctl is-enabled nftables-singbox.service >/dev/null 2>&1; then
        echo -e "${CYAN}Сервис автозапуска Nftables-singbox включен${RESET}"
    else
        echo -e "${PURPLE}Сервис автозапуска Nftables-singbox отключен${RESET}"
    fi
  else
    echo -e "${RED}Сервис автозапуска Nftables-singbox не установлен!${RESET}"
  fi

 if command -v nft >/dev/null 2>&1; then
    systemctl is-active nftables >/dev/null 2>&1 && echo -e "${CYAN}Фаервол Nftables запущен${RESET}" || echo -e "${PURPLE}Фаервол Nftables не запущен${RESET}"
 else
    echo -e "${RED}Фаервол Nftables не установлен!${RESET}"
 fi

   UPDATE_SCRIPT="/etc/sing-box/update-singbox.sh"
   if [ -f "$UPDATE_SCRIPT" ]; then
       if crontab -l 2>/dev/null | grep -q "$UPDATE_SCRIPT"; then
        echo -n -e "${GREEN}Автоматическое обновление настроек настроено${RESET}"
        INTERVAL=$(crontab -l 2>/dev/null | grep "$UPDATE_SCRIPT" | grep -oE '\*/[0-9]+' | sed 's|\*/||')
        [[ -n "$INTERVAL" ]] && echo -n -e " ${CYAN}Интервал обновления:${RESET} ${INTERVAL} часов" || echo -e " ${RED}Не удалось получить время обновления!${RESET}"
       else
        echo -n -e "${RED}Автоматическое обновление настроек не настроено!${RESET}"
       fi
       LAST_UPDATE=$(stat -c %y "$UPDATE_SCRIPT" 2>/dev/null | cut -d'.' -f1)
       [[ -n "$LAST_UPDATE" ]] && echo -e " ${CYAN}Последнее обновление:${RESET} ${LAST_UPDATE}" || echo -e " ${RED}Не удалось получить время последнего обновления!${RESET}"
   else
    echo -e "${RED}Файл автоматического обновления отсутствует!${RESET}"
   fi
}

check_system_resources() {
    echo -e "\n${CYAN}Информация о системных ресурсах:${RESET}"
    CPU_INFO=$(top -bn1 | grep "Cpu(s)" | awk '{if (NF >= 8) printf "Использование: %.1f%%, Свободно: %.1f%%", $2, $8}')
    echo -e "${BLUE}Состояние CPU:${RESET} ${CPU_INFO}"
    MEM_INFO=$(free -h | awk '/^Mem/ {printf "%s/%s (%.1f%%)", $3, $2, $3/$2*100}')
    echo -e "${BLUE}Использование памяти:${RESET} ${MEM_INFO}"
    DISK_INFO=$(df -h / 2>/dev/null | awk 'NR==2 {print $5}')
    echo -e "${BLUE}Использование диска:${RESET} ${DISK_INFO}"
}

check_network() {
    echo -e "\n${CYAN}Информация о сети:${RESET}"
    DEFAULT_GATEWAY=$(ip route | awk '/default/ {print $3}')
    GATEWAY_INTERFACE=$(ip route | awk '/default/ {print $5}')
    [[ -n "$DEFAULT_GATEWAY" ]] && echo -e "${BLUE}Шлюз по умолчанию:${RESET} ${DEFAULT_GATEWAY}\n${BLUE}Интерфейс шлюза:${RESET} ${GATEWAY_INTERFACE}" || echo -e "${RED}Информация о шлюзе по умолчанию не найдена!${RESET}"
    if [[ -f /run/systemd/resolve/resolv.conf ]]; then
        DNS_SERVERS=$(grep '^nameserver' /run/systemd/resolve/resolv.conf | awk '{print $2}')
    else
        DNS_SERVERS=$(grep '^nameserver' /etc/resolv.conf | awk '{print $2}')
    fi
    [[ -n "$DNS_SERVERS" ]] && echo -e "${BLUE}DNS серверы:${RESET}\n$DNS_SERVERS" || echo -e "${RED}Информация о DNS серверах не найдена!${RESET}"
}

check_singbox
check_services
check_system_resources
check_network
